name: production-deploy

on:
  push:
    tags:
      - v*

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: execute tests
        run: echo Test ecexution ⚙️

  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      - name: build and deploy
        env:
          ENV: production
          SWARM_HOST: 156.54.237.240
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
          AWS_REGION: eu-central-1
          SWARM_PEM: ${{secrets.AI_PRODUCTION_PEM}}
          SHAREPOINT_ID: ${{secrets.SHAREPOINT_ID}}
          ECR_URI: ${{secrets.ECR_URI}}
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${SWARM_PEM}"
          mkdir ~/.ssh
          echo "ssh directory created"
          ssh-keyscan -p 2222 -H $SWARM_HOST >> ~/.ssh/known_hosts
          echo "ssh key added"
          echo "running deploy.sh $ENV"
          sh deploy.sh $ENV
